format_version: 10
pipelines:
  expense-tf-apply:
    group: Terraform
    materials:
      git-b844969:
        git: https://github.com/DevOps-iteration1/expense-terraform.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      TF_VAR_vault_token: AES:tRFYdKNbm847TIJ/sVs9Zg==:sRXYPM1ynmQT4XHrekBhrpuFfzUyzVz81V5YkX6jQHLsp4NVmqf1YOITOcyLQ246
    stages:
      - DEV:
          fetch_materials: true
          environment_variables:
            env : dev
          approval:
            type: manual
          jobs:
            terraform-apply:
              tasks:
                - exec: {command: terraform, arguments: ["init", "-backend-config=env-dev/state.tfvars"], run_if: passed}
                - exec: {command: terraform, arguments: ["apply", "-var-file=env-dev/main.tfvars","-auto-approve"], run_if: passed}
