format_version: 10
pipelines:
  expense-tf-destroy:
    group: Terraform
    materials:
      git-b844969:
        git: https://github.com/DevOps-iteration1/expense-terraform.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      TF_VAR_vault_token: AES:p5w3xpd1h78xAyNggBiGkg==:ZFKICRRrr5OA14zf1x9UjpVR/OVDsi/jaZGF9+qgDaH1ca1tJdgW+mhvaBsc0SAf
    stages:
      - DEV:
          fetch_materials: true
          environment_variables:
            env : dev
          approval:
            type: manual
          jobs:
            terraform-apply:
              tasks:
                - exec: {command: terraform, arguments: ["init", "-backend-config=env-dev/state.tfvars"],run_if: passed}
                - exec: {command: terraform, arguments: ["destroy", "-var-file=env-dev/main.tfvars","-auto-approve"],run_if: passed}
